network:
  ethernets:
     ens33:
        dhcp4: false
        addresses:
          - 192.168.1.125/24
        routes: 
          - to: default
            via: 192.168.1.2
        nameservers:
          addresses: [8.8.8.8, 8.8.4.4]
  version: 2